#!bin/bash

set -e

psql - ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER IF NOT EXISTS $POSTGRES_USER
	CREATE DATABASE IF NOT EXISTS $POSTGRES_DB;
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
EOSQL