version: "3"
services:

  backend:
    build: ./
    container_name: oauth_backend
    ports:
      - 3345:80
    networks:
      - oauth2
    command: ["pm2", "runtimes", ""]

  frontend:
    build: ./
    container_name: oauth_frontend
    ports:
      - 3333:80
    networks:
      - oauth2
    command: ["pm2", "runtimes", ""]


networks:
  oauth: