version: "3"
services:

  builder:
    container_name: oauth_builder
    restart: always
    build: ./
    volumes:
        - ./backend:/app
    networks:
        - oauth
    command: sh -c "npm i && npm run dev"

  backend:
    container_name: oauth_backend
    restart: always
    build: ./
    depends_on: 
      - builder
    ports:
        - 3345:3333
    volumes:
        - ./backend:/app
        - ./docker/tmp/logs/:/usr/src/app/error.log
    networks:
        - oauth
    command: ["pm2-runtime", "process.json"]

  frontend:
    build: ./
    container_name: oauth_frontend
    volumes:
        - ./frontend:/app
    ports:
      - 3000:3333
    networks:
      - oauth
    command: sh -c "npm i && npm run dev"

  postgres:
    image: postgres
    container_name: oauth_pgsql
    restart: always
    volumes:
      - oauth_data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=oauth
      - POSTGRES_USER=oauth
      - POSTGRES_DB=oauth
    ports:
      - 5432:5432
    networks:
      - oauth

volumes:
  oauth_data:

networks:
  oauth: