version: "3"
services:

  builder:
    container_name: oauth_builder
    restart: always
    build: ./
    volumes:
        - ./backend:/app
    networks:
        - backend
    command: sh -c "yarn && yarn dev"

  backend:
    container_name: oauth_backend
    restart: always
    build: ./
    depends_on: 
      - builder
    ports:
        - 3333:3333
    volumes:
        - ./backend:/app
        - ./docker/tmp/logs/:/usr/src/app/error.log
    networks:
        - backend
    command: ["pm2-runtime", "process.json"]

  frontend:
    build: ./
    container_name: oauth_frontend
    ports:
      - 3000:3333
    networks:
      - oauth2
    command: ["pm2-runtime", "process.json"]

  postgres:
    image: postgres
    container_name: oauth_pgsql
    restart: always
    volumes:
      - ./docker/db/PGSQL/data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DATABASE=oauth
    ports:
      - 5434:5432
    networks:
      - oauth

networks:
  oauth: