version: "3"
services:

  builder:
    container_name: oauth_builder
    build: 
      context: ./
      target: oauth_builder
    restart: always
    volumes:
        - ./backend:/usr/src/app
    networks:
        - network
    command: sh -c "npm run dev"

  backend:
    container_name: oauth_backend
    restart: always
    build: 
      context: ./
      target: oauth_backend
    depends_on: 
      - builder
    ports:
        - 3345:3333
    volumes:
        - ./backend:/usr/src/app
    networks:
        - network

  frontend:
    container_name: oauth_frontend
    build: 
      context: ./
      target: oauth_frontend
    restart: always
    volumes:
        - ./frontend:/usr/src/app
    ports:
      - 3000:3333
    networks:
      - network

  postgres:
    image: postgres
    container_name: oauth_pgsql
    restart: always
    volumes:
      - pgsql_data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=oauth
      - POSTGRES_USER=oauth
      - POSTGRES_DB=oauth
    ports:
      - 5432:5432
    networks:
      - network

volumes:
  pgsql_data:

networks:
  network: